In [1]:
import pandas as pd

df = pd.read_feather('exp2_glue_scores.arrow') * 100

In [9]:
GLUE_SCORE_FULL = [
    ('mrpc', 'eval_combined_score'),
    ('cola', 'eval_matthews_correlation'),
    ('mnli', 'eval_accuracy'),
    ('mnli', 'eval_accuracy_mm'),
    ('qqp', 'eval_combined_score'),
    ('rte', 'eval_accuracy'),
    ('stsb', 'eval_combined_score'),
    ('qnli', 'eval_accuracy'),
    ('sst2', 'eval_accuracy'),
    ('wnli', 'eval_accuracy'),
]
GLUE_SCORE_BERT = [
    ('mrpc', 'eval_combined_score'),
    ('cola', 'eval_matthews_correlation'),
    ('mnli', 'eval_accuracy'),
    ('mnli', 'eval_accuracy_mm'),
    ('qqp', 'eval_combined_score'),
    ('rte', 'eval_accuracy'),
    ('stsb', 'eval_combined_score'),
    ('qnli', 'eval_accuracy'),
    ('sst2', 'eval_accuracy'),
]

df[('glue_score', 'full')] = df[GLUE_SCORE_FULL].apply(lambda x: x.mean(), axis=1)
df[('glue_score', 'bert')] = df[GLUE_SCORE_BERT].apply(lambda x: x.mean(), axis=1)

In [10]:
df['glue_score']

metric                                     full  bert
model                                seed
bert_base_pairwise_20240204-093411   1    74.66 79.67
                                     2    73.75 79.44
                                     3    74.56 79.08
                                     4    76.97 79.73
                                     5    74.66 78.88
bert_base_symmetric_20240204-093411  1    71.12 74.18
                                     2    70.52 74.91
                                     3    70.60 75.00
                                     4    73.06 75.07
                                     5    71.24 74.93
bert_base_vanilla_20240204-093411    1    74.96 79.53
                                     2    73.97 78.59
                                     3    72.59 77.84
                                     4    75.80 79.06
                                     5    74.04 78.67
bert_small_pairwise_20240204-194202  1    70.20 73.78
                                     2    70.41 73.69
                                     3    70.60 73.44
                                     4    70.71 72.93
                                     5    69.00 73.06
bert_small_symmetric_20240204-194202 1    67.28 70.06
                                     2    66.26 69.40
                                     3    66.15 69.58
                                     4    68.42 69.76
                                     5    66.11 69.23
bert_small_vanilla_20240204-194202   1    68.58 72.76
                                     2    68.80 72.68
                                     3    69.25 72.72
                                     4    70.84 72.61
                                     5    69.19 72.80

In [11]:
df['glue_score'].groupby('model').agg(['mean','std'])

metric                                full       bert
                                      mean  std  mean  std
model
bert_base_pairwise_20240204-093411   74.92 1.21 79.36 0.37
bert_base_symmetric_20240204-093411  71.31 1.03 74.82 0.36
bert_base_vanilla_20240204-093411    74.27 1.20 78.74 0.63
bert_small_pairwise_20240204-194202  70.18 0.69 73.38 0.37
bert_small_symmetric_20240204-194202 66.84 1.00 69.61 0.32
bert_small_vanilla_20240204-194202   69.33 0.89 72.72 0.07

In [13]:
df[GLUE_SCORE_FULL].groupby('model').agg(['mean'])

task                                                mrpc  \
metric                               eval_combined_score
                                                    mean
model
bert_base_pairwise_20240204-093411                 87.83
bert_base_symmetric_20240204-093411                78.36
bert_base_vanilla_20240204-093411                  85.30
bert_small_pairwise_20240204-194202                82.34
bert_small_symmetric_20240204-194202               76.81
bert_small_vanilla_20240204-194202                 81.04

task                                                      cola          mnli  \
metric                               eval_matthews_correlation eval_accuracy
                                                          mean          mean
model
bert_base_pairwise_20240204-093411                       46.91         81.60
bert_base_symmetric_20240204-093411                      35.22         78.66
bert_base_vanilla_20240204-093411                        44.35         81.66
bert_small_pairwise_20240204-194202                      24.21         76.37
bert_small_symmetric_20240204-194202                     10.29         75.25
bert_small_vanilla_20240204-194202                       21.39         77.16

task                                                                  qqp  \
metric                               eval_accuracy_mm eval_combined_score
                                                 mean                mean
model
bert_base_pairwise_20240204-093411              82.02               88.89
bert_base_symmetric_20240204-093411             79.05               87.70
bert_base_vanilla_20240204-093411               82.07               88.86
bert_small_pairwise_20240204-194202             76.89               86.67
bert_small_symmetric_20240204-194202            75.72               85.13
bert_small_vanilla_20240204-194202              77.76               86.08

task                                           rte                stsb  \
metric                               eval_accuracy eval_combined_score
                                              mean                mean
model
bert_base_pairwise_20240204-093411           60.58               86.88
bert_base_symmetric_20240204-093411          53.43               84.47
bert_base_vanilla_20240204-093411            59.42               87.30
bert_small_pairwise_20240204-194202          56.25               84.13
bert_small_symmetric_20240204-194202         55.74               77.83
bert_small_vanilla_20240204-194202           54.87               82.20

task                                          qnli          sst2          wnli
metric                               eval_accuracy eval_accuracy eval_accuracy
                                              mean          mean          mean
model
bert_base_pairwise_20240204-093411           88.78         90.78         34.93
bert_base_symmetric_20240204-093411          86.90         89.56         39.72
bert_base_vanilla_20240204-093411            88.76         90.92         34.08
bert_small_pairwise_20240204-194202          84.97         88.60         41.41
bert_small_symmetric_20240204-194202         82.79         86.90         41.97
bert_small_vanilla_20240204-194202           85.45         88.49         38.87

In [6]:
df[GLUE_SCORE_FULL].groupby('model').agg(['mean','std']).apply

\begin{tabular}{lrrrrrrrrrrrrrrrrrrrr}
\toprule
task & \multicolumn{2}{r}{mrpc} & \multicolumn{2}{r}{cola} & \multicolumn{4}{r}{mnli} & \multicolumn{2}{r}{qqp} & \multicolumn{2}{r}{rte} & \multicolumn{2}{r}{stsb} & \multicolumn{2}{r}{wnli} & \multicolumn{2}{r}{qnli} & \multicolumn{2}{r}{sst2} \\
metric & \multicolumn{2}{r}{eval_combined_score} & \multicolumn{2}{r}{eval_matthews_correlation} & \multicolumn{2}{r}{eval_accuracy} & \multicolumn{2}{r}{eval_accuracy_mm} & \multicolumn{2}{r}{eval_combined_score} & \multicolumn{2}{r}{eval_accuracy} & \multicolumn{2}{r}{eval_combined_score} & \multicolumn{2}{r}{eval_accuracy} & \multicolumn{2}{r}{eval_accuracy} & \multicolumn{2}{r}{eval_accuracy} \\
 & mean & std & mean & std & mean & std & mean & std & mean & std & mean & std & mean & std & mean & std & mean & std & mean & std \\
model &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
bert_base_pairwise_20240204-093411 & 87.829602 & 1.141476 & 46.914140 & 1.717909 & 81.595517 & 0.277774 & 82.017901 & 0.193514 & 88.885583 & 0.164670 & 60.577617 & 2.141862 & 86.880412 & 0.180773 & 34.929577 & 10.973268 & 88.782720 & 0.309403 & 90.779817 & 0.559464 \\
bert_base_symmetric_20240204-093411 & 78.359886 & 1.243183 & 35.218168 & 3.296141 & 78.661233 & 0.307567 & 79.045972 & 0.377927 & 87.696183 & 0.120068 & 53.429603 & 1.197337 & 84.474278 & 0.514595 & 39.718310 & 10.028723 & 86.897309 & 0.187302 & 89.564220 & 0.243271 \\
bert_base_vanilla_20240204-093411 & 85.296385 & 1.516104 & 44.352091 & 2.123935 & 81.664799 & 0.248482 & 82.068755 & 0.347749 & 88.857394 & 0.157364 & 59.422383 & 4.752471 & 87.301708 & 0.278393 & 34.084507 & 7.675733 & 88.757093 & 0.111645 & 90.917431 & 0.468643 \\
bert_small_pairwise_20240204-194202 & 82.339619 & 0.751673 & 24.211820 & 1.491840 & 76.370861 & 0.239960 & 76.893816 & 0.396103 & 86.672684 & 0.106009 & 56.245487 & 3.781147 & 84.126563 & 0.316899 & 41.408451 & 6.942962 & 84.967966 & 0.441487 & 88.600917 & 0.340193 \\
bert_small_symmetric_20240204-194202 & 76.812719 & 0.962867 & 10.286751 & 3.025822 & 75.250127 & 0.250955 & 75.716029 & 0.289790 & 85.133021 & 0.062707 & 55.740072 & 2.129658 & 77.825975 & 0.558545 & 41.971831 & 8.415419 & 82.793337 & 0.892731 & 86.903670 & 0.528021 \\
bert_small_vanilla_20240204-194202 & 81.040791 & 0.523764 & 21.393374 & 1.307790 & 77.159450 & 0.218210 & 77.762408 & 0.243103 & 86.082817 & 0.086747 & 54.873646 & 1.893157 & 82.196742 & 0.311497 & 38.873239 & 9.374401 & 85.454878 & 0.210944 & 88.486239 & 0.418224 \\
\bottomrule
\end{tabular}

In [7]:
pd.options.display.float_format = "{:,.2f}".format

In [ ]:
81.04($\pm$0.52)	21.39($\pm$1.31)	77.16($\pm$0.22)	77.76($\pm$0.24)	86.08($\pm$0.09)	54.87($\pm$1.89)	82.20($\pm$0.31)	38.87($\pm$9.37)	85.45($\pm$0.21)	88.49($\pm$0.42)